runners:
  - name: azure-cpu-runner-spotinstance
    cloud: azure
    instance_type: D8ads_v6
    machine_image: Canonical:UbuntuServer:24.04-LTS:latest
    preemptible: true
    labels:
      - x86-64-lg-testing
